### ISSUE TITLE
Message Card

### ISSUE THREAD

**Issue by RedMaps** [Kaichou-Project/kaichou-graduation#19]
![image](https://user-images.githubusercontent.com/16868419/122266172-d1527800-ced9-11eb-8eb3-549e20039edb.png)

**Comment by LiAustin059** [comment]
I'll try to work on this

**Comment by LiAustin059** [comment]
Weird request but for someone that knows what they are doing can you check my code so far, I just wanna make sure I'm on the right track with what needs to be done and not spending time doing something random that is incorrect for this.
![image](https://user-images.githubusercontent.com/44851962/122322950-4f237d00-cef4-11eb-8780-6c27493a8872.png)

**Comment by RedMaps** [comment]
That really looks fine as far as I can tell.
