### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by RedMaps** [Kaichou-Project/kaichou-graduation#20]
![image](https://user-images.githubusercontent.com/16868419/122266266-e9c29280-ced9-11eb-983c-c12f6515d405.png)

**Comment by TakoLeakest** [comment]
Working on it.

**Comment by RedMaps** [comment]
Be sure to know that the active element always has the dot below it. Also you can click on the icons in figma and scroll all the way down to export them so you can use them in the code.

**Comment by TakoLeakest** [comment]
Yeah, I guess I should've checked that feature of Figma instead of messing with SCSS for hours...

But now it's looking good!
