### ISSUE TITLE
Make progress bar on sound player work.

### ISSUE THREAD

**Issue by RedMaps** [Kaichou-Project/kaichou-graduation#25]
The audio players for the soundboard should display the current clip position at the bottom.

![image](https://user-images.githubusercontent.com/16868419/122370593-77949100-cf5f-11eb-89fd-488f09a48271.png)

**Comment by yovic4** [comment]
oh that's a progress bar, thought It was just some line for design lol. I'll take this then

**Comment by RedMaps** [comment]
Perfect, thank you lmao
