### ISSUE TITLE
Make the links in the implemented footer functional

### ISSUE THREAD

**Issue by RedMaps** [Kaichou-Project/kaichou-graduation#26]
We have a fully implemented footer. Now it's just missing the links to the actual stuff.
Please use [next/link](https://nextjs.org/docs/api-reference/next/link) for this purpose.

![image](https://user-images.githubusercontent.com/16868419/122374904-0b1b9100-cf63-11eb-9524-0da1d464d33d.png)

**Comment by keijeizei** [comment]
I'll work on this.
