### ISSUE TITLE
API Endpoint for Message (Backend)

### ISSUE THREAD

**Issue by nyxordinal** [Kaichou-Project/kaichou-graduation#40]
Create two new API endpoints in backend:
- Endpoint for updating the message (using PUT http method)
- Endpoint for deleting the message (using DELETE http method)

Notes:
- you can use existing endpoint for reference
- if in your endpoint there is request body required, always make sure you validate it in controller before passing request body value to the service
- use appropriate response util

**Comment by yovic4** [comment]
I want to try to do this one if you don't mind

**Comment by nyxordinal** [comment]
sure, good luck
