### ISSUE TITLE
API Endpoint for Video (Backend)

### ISSUE THREAD

**Issue by nyxordinal** [Kaichou-Project/kaichou-graduation#41]
Create four new API endpoints in backend:
- Endpoint for fetching all video (using GET http method)
- Endpoint for creating new video (using POST http method)
- Endpoint for updating the video (using PUT http method)
- Endpoint for deleting the video (using DELETE http method)

Notes:
- you can use existing endpoint for reference
- if in your endpoint there is request body required, always make sure you validate it in controller before passing request body value to the service
- use appropriate response util

**Comment by GlennPoh** [comment]
@nyxordinal Hi there are u working on this? If not I would like to give it a try

**Comment by nyxordinal** [comment]
I think this issue still unoccupied, I'll assign you to this issue then

**Comment by nyxordinal** [comment]
Good luck !

**Comment by GlennPoh** [comment]
Alright!
