### ISSUE TITLE
Unit Test in Backend

### ISSUE THREAD

**Issue by nyxordinal** [Kaichou-Project/kaichou-graduation#44]
We'll start implementing unit tests on backend as the service grows bigger  
Unit test will using [jest framework](https://jestjs.io/)
What you have to do is write the test code for each service and controller , and integate it with the husky pre-commit

Note:  
if anyone has any other recommendations for testing framework in node js, let me know in the comment section

**Comment by FomTarro** [comment]
Sign me up, buttercup.
