### ISSUE TITLE
Forms check confirm

### ISSUE THREAD

**Issue by Holo-23** [Kaichou-Project/kaichou-graduation#50]
https://github.com/Kaichou-Project/kaichou-graduation/blob/7b4528c78743ad049d72f83b249accc6d729adef/packages/frontend/components/Forms/CheckConfirm.tsx#L17-L21
Shouldn't we capitalize the letter "I" in "...i have explicit permission..."? I was looking through it and I thought it was kinda odd

**Comment by TakoLeakest** [comment]
Yes, I think we should...

**Comment by RedMaps** [comment]
Agreed. I'll probably fix this in the next code overhaul ^^
