### ISSUE TITLE
Captcha submission verification

### ISSUE THREAD

**Issue by azuraga** [Kaichou-Project/kaichou-graduation#52]
Every submission needs to be captcha verified to prevent bots from spamming.

**Comment by yovic4** [comment]
What library usually used to make this?

**Comment by TakoLeakest** [comment]
What about Google ReCaptcha? Or are we looking for FOSS alternatives?

**Comment by azuraga** [comment]
This should be made on API level to prevent circumvention by directly going to the endpoint

**Comment by TakoLeakest** [comment]
What if we enable CORS only to the website were the Front-End will be hosted? Can that work to avoid using the endpoint directly from somewhere else?

**Comment by yovic4** [comment]
Ok, how about for frontend we use [react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha). I think this should give us a token we can use to validate the captcha. So we send this token to the backside along with data, and verify the token like [this](https://developers.google.com/recaptcha/docs/verify). So, even if some1 directly uses the endpoint, he/she shouldn't have a valid token and is going to be rejected

**Comment by RedMaps** [comment]
What yovic said is basically exactly what I was thinking.
