### ISSUE TITLE
Improvements for MessageBoard

### ISSUE THREAD

**Issue by Mecki-Messer** [Kaichou-Project/kaichou-graduation#7]
refactor code to reflect naming conventions of ERD
work on REST API
work on adding support for videos and images in the submit section

**Comment by Mecki-Messer** [comment]
code refactoring done,
support for video and image added
test pages removed

**Comment by azuraga** [comment]
> support for video and image added

Is this the same as issue #18 ?

**Comment by Mecki-Messer** [comment]
basically, it was started before video and images were added. ill close it because it became redundant
