### ISSUE TITLE
Responsive Fonts

### ISSUE THREAD

**Issue by Mecki-Messer** [Kaichou-Project/kaichou-graduation#74]
We should probably work on responsive fonts for the page. I have read about some librarys that should work fine for it. I can look into this further and report my findings, i will probably also implement it for the clips page as well.
Is there anything that I have to look out for?

**Comment by keijeizei** [comment]
Does this mean the scaling of the fonts depending on the screen width? Maybe we can just use `vw` as font sizes or add breakpoints in the main css file to change font size using `px` and then use `em` and `rem` as font sizes for all text.
In case this is about adding `...` on text when it overflows, we can just add something like `text-overflow: ellipsis;` on the css.

**Comment by Mecki-Messer** [comment]
that is exactly the question. is there a necessity for another library just to scale fonts? it seemed to me like the "vanilla" ways of doing it are overly complicated but then again adding another dependency might be overkill

**Comment by keijeizei** [comment]
I think I managed to do this using css breakpoints. Will add this in PR #85 . Do check if that is what you are looking for.
