### ISSUE TITLE
Adding Title Property in Video Model

### ISSUE THREAD

**Issue by nyxordinal** [Kaichou-Project/kaichou-graduation#78]
There is a need to store the video title in the DB, basically what will have to do is :
* add new property `title` in Video Model in Backend
* add new input in Video/Clip submission form in Frontend

**Comment by josef-yu** [comment]
Let me work on this. Should I also work on the changes of controllers and services?

**Comment by josef-yu** [comment]
Should I also work on the changes of the controllers and services?

**Comment by nyxordinal** [comment]
> Let me work on this. Should I also work on the changes of controllers and services?

I think this issue already done, I'm sorry

**Comment by nyxordinal** [comment]
Thank you for the willingness 👍
