### ISSUE TITLE
Fixing size, gaps etc

### ISSUE THREAD

**Issue by yovic4** [Kaichou-Project/kaichou-graduation#92]
Now that most of the pages is made, I think we need tidy up a lot of things. This includes adjusting font sizes #74 and adjusting margin and padding so that the gap is more uniform across component (current there are component with no gap or too much gap)

**Comment by keijeizei** [comment]
I'm working on the uniform font sizes. Currently on #85

**Comment by yovic4** [comment]
Can you fix the gaps sizes too?

**Comment by keijeizei** [comment]
Will do. Just leave a review later if I miss some
